image: golang:1.11-stretch

stages:
  - build

variables:
  LIBPCAP_VERSION: "1.9.1"
  ARTIFACT_NAME_TEMPLATE: "$CI_JOB_NAME"
  GO_IMAGE: "golang:1.11-stretch"
  PACKAGES: "software-properties-common byacc flex dpkg-dev python3 python3-pip debhelper"

build_amd64:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - sudo apt-get update
    - sudo apt-get install -y $PACKAGES libpcap0.8 libpcap-dev
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - make deps
  script:
    - make build
    - make debian
  after_script:
    - mv bin/netspot bin/netspot-amd64
    - mv bin/netspotctl bin/netspotctl-amd64
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot
      - bin/netspotctl
      - dist/debian/*.deb
      - $CI_JOB_NAME.svg

build_armhf:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y $PACKAGES linux-libc-dev-armhf-cross gcc-arm-linux-gnueabihf
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=arm-linux-gnueabihf-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=arm-linux-gnueabihf-gcc make
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - cd /go/src/netspot
    - make deps
    - export CC=arm-linux-gnueabihf-gcc
    - export GOOS=linux
    - export GOARCH=arm
    - export GOARM=7
  script:
    - make build
    - LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib make debian
  after_script:
    - mv bin/netspot bin/netspot-armhf
    - mv bin/netspotctl bin/netspotctl-armhf
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot-armhf
      - bin/netspotctl-armhf
      - dist/debian/*.deb
      - $CI_JOB_NAME.svg

build_aarch64:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y $PACKAGES linux-libc-dev-arm64-cross gcc-aarch64-linux-gnu
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - make deps
    - cd /tmp
    - export CC=aarch64-linux-gnu-gcc
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - ./configure --host=arm-linux --with-pcap=linux
    - make
    - cd /go/src/netspot
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - export GOOS=linux
    - export GOARCH=arm64
  script:
    - make build
    - LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib make debian
  after_script:
    - mv bin/netspot bin/netspot-aarch64
    - mv bin/netspotctl bin/netspotctl-aarch64
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot-aarch64
      - bin/netspotctl-aarch64
      - dist/debian/*.deb
      - $CI_JOB_NAME.svg

docker:
  image: docker:stable
  stage: build
  only:
    - web
  services:
    - docker:dind
  before_script:
    - docker info
  script: make docker
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - dist/docker/*
