image: golang:1.11-stretch

stages:
  - build

variables:
  LIBPCAP_VERSION: "1.9.1"
  ARTIFACT_NAME_TEMPLATE: "$CI_JOB_NAME"
  GO_IMAGE: "golang:1.11-stretch"
  PACKAGES: "software-properties-common byacc flex dpkg-dev python3-pip debhelper"

build_amd64:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y $PACKAGES
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - make deps
  script:
    - make build
  after_script:
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot
      - bin/netspotctl
      - $CI_JOB_NAME.svg

build_armhf:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y $PACKAGES linux-libc-dev-armhf-cross gcc-arm-linux-gnueabihf
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=arm-linux-gnueabihf-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=arm-linux-gnueabihf-gcc make
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - cd /go/src/netspot
    - make deps
    - export CC=arm-linux-gnueabihf-gcc
    - export GOOS=linux
    - export GOARCH=arm
    - export GOARM=7
  script:
    - make build
    - LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib make debian
  after_script:
    - mv bin/netspot bin/netspot-armhf
    - mv bin/netspotctl bin/netspotctl-armhf
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot-armhf
      - bin/netspotctl-armhf
      - dist/debian/*.deb
      - $CI_JOB_NAME.svg

build_aarch64:
  stage: build
  image: $GO_IMAGE
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y $PACKAGES linux-libc-dev-arm64-cross gcc-aarch64-linux-gnu
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=aarch64-linux-gnu-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=aarch64-linux-gnu-gcc make
    - cd /go/src/netspot
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - make deps
  script:
    - CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 make build
  after_script:
    - mv bin/netspot bin/netspot-aarch64
    - mv bin/netspotctl bin/netspotctl-aarch64
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot-aarch64
      - bin/netspotctl-aarch64
      - $CI_JOB_NAME.svg
# build_docker:
#   stage: docker
#   image: docker:19.03.1
#   only:
#     - web
#   before_script:
#     - docker info
#   script:
#     - make docker
#   artifacts:
#     name: $ARTIFACT_NAME_TEMPLATE
#     paths:
#       - dist/docker/docker-netspot*

# build_debian:
#   stage: build
#   image: $GO_IMAGE
#   only:
#     - web
#   before_script:
#     - apt-get update
#     - apt-get install -y software-properties-common libpcap-dev dpkg-dev python3-pip
#     - pip3 install pybadges
#     - ln -s /builds/asr/netspot /go/src/netspot
#     - make deps
#   script:
#     - make debian
#   artifacts:
#     name: $ARTIFACT_NAME_TEMPLATE
#     paths:
#       - dist/debian/netspot*
