image: golang:1.11-stretch

stages:
  - build

variables:
  LIBPCAP_VERSION: "1.9.1"
  ARTIFACT_NAME_TEMPLATE: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"

build-amd64:
  stage: build
  image: golang:1.11-stretch
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y sudo software-properties-common libpcap-dev python3-pip
    - pip3 install pybadges
    - ln -s /builds/asr/netspot /go/src/netspot
  script:
    - pwd
    - make deps
    - make build
    - python3 .badge.gitlab-ci.py -d /go/src/netspot/bin -a $CI_JOB_NAME -o $CI_JOB_NAME.svg
    - ls -al .
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot
      - bin/netspotctl
      - $CI_JOB_NAME.svg

build-armhf:
  stage: build
  image: golang:1.11-stretch
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y sudo software-properties-common gcc-arm-linux-gnueabihf byacc flex
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=arm-linux-gnueabihf-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=arm-linux-gnueabihf-gcc make
  script:
    - cd /go/src/netspot
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - make deps
    - CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm GOARM=7 make build
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot
      - bin/netspotctl

build-aarch64:
  stage: build
  image: golang:1.11-stretch
  only:
    - web
  before_script:
    - apt-get update
    - apt-get install -y sudo software-properties-common gcc-aarch64-linux-gnu byacc flex
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=aarch64-linux-gnu-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=aarch64-linux-gnu-gcc make
  script:
    - cd /go/src/netspot
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - make deps
    - CC=aarch64-linux-gnu-gcc GOOS=linux GOARCH=arm64 make build
  artifacts:
    name: $ARTIFACT_NAME_TEMPLATE
    paths:
      - bin/netspot
      - bin/netspotctl
