image: golang:1.11-stretch

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y software-properties-common python3-software-properties
  - add-apt-repository ppa:asiffer/libspot
  - apt-get update 
  - apt-get install -y libspot make
  - mkdir -p /go/src/gitlab.com
  - mkdir -p /go/src/github.com
  - go get -u github.com/c-bata/go-prompt
  - go get -u github.com/rs/zerolog
  - go get -u github.com/spf13/viper
  - go get -u github.com/fatih/color
  - go get -u github.com/fsnotify/fsnotify
  - go get -u github.com/urfave/cli
  - go get -u github.com/influxdata/influxdb/client/v2
  - ln -s /builds/user /go/src/gitlab.com/user

coverage:
  stage: test
  script:
    - go test -cover -v ./...