image: golang:1.11-stretch

stages:
  - build

build-amd64:
  stage: build
  image: golang:1.11-stretch
  script:
    - pwd
    - make deps
    - make build
  before_script:
    - apt-get update
    - apt-get install -y sudo software-properties-common libpcap-dev
    - ln -s /builds/asr/netspot /go/src/netspot
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - bin/netspot
      - bin/netspotctl

build-armhf:
  stage: build
  image: golang:1.11-stretch
  variables:
    LIBPCAP_VERSION: "1.9.1"
  before_script:
    - apt-get update
    - apt-get install -y sudo software-properties-common gcc-arm-linux-gnueabihf byacc flex
    - ln -s /builds/asr/netspot /go/src/netspot
    - cd /tmp
    - wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
    - tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
    - cd libpcap-$LIBPCAP_VERSION
    - CC=arm-linux-gnueabihf-gcc ./configure --host=arm-linux --with-pcap=linux
    - CC=arm-linux-gnueabihf-gcc make
    - sudo make install
  script:
    - cd /go/src/netspot
    - export CGO_ENABLED=1
    - export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
    - export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
    - make deps
    - CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm GOARM=7 make build
  artifacts:
    name: "$CI_JOB_STAGE-$CI_COMMIT_REF_NAME"
    paths:
      - bin/netspot
      - bin/netspotctl
