# netspot config file

[analyzer]
# time between two statistics computations
period = "3s"
# stats to load at startup
stats = ["AVG_PKT_SIZE"]
#stats = ["R_SYN", "R_ACK"]
#stats = []

[analyzer.datalog]
# send data to influxdb database
influxdb = false
# log data to files
file = true
output_dir = "/tmp" # file mode only

[miner]
# name of the interface to listen or dump/pcap file path
#device = "enp2s0"
device = "enx84a93e22a3fb"
# interface only
promiscuous = true
snapshot_len = 65535
timeout = "20s"

[influxdb]
# influxdb server details
addr = "127.0.0.1"
port = 8086
database = "netspot"
username = "netspot"
password = "netspot"
# number of data to store before sending
batch_size = 10
# the agent_name is just a tag for influxdb
agent_name = "unknown"


[dspot]
# default values of DSpot
depth = 10
q = 1e-4
n_init = 1000
level = 0.98
up = true
down = false
alert = true
bounded = true
max_excess = 200

# you can define default values for some stats
# [spot.R_SYN]
# q = 2e-5


