
# the Miner module manages the packets parsing
# and the counters
[miner]
# name of the interface to listen or dump/pcap file path
#device = "eno1"
#device = "/path/to/pcap/file"
# interface only
#promiscuous = true
#snapshot_len = 65535
#timeout = "20s"

# The Analyzer module manages the statistics
# and send data to the exporter
[analyzer]
# time between two statistics computations
period = "1s"
# stats to load at startup
#stats = ["AVG_PKT_SIZE"]
stats = ["PERF", "R_SYN", "R_ACK"]
#stats = []

# spot section manages the default spot parameters
[spot]
# depth = 50
# q = 1e-4
# n_init = 1000
# level = 0.98
# up = true
# down = false
# alert = true
# bounded = true
# max_excess = 200
# you can add a specific section for a statistic
# it overrides the default values
# [spot.R_SYN]
# q = 1e-5

# The exporter print or send data according
# to the loaded modules (and their options)
# [exporter]
[exporter.console]
# print data to the console
data = true
# print alarms to the console
alarm = true

[exporter.file]
# Path to the file which will store the data.
# The value can contain a '%s' which will be replaced by 
# the series name. 
data = "/tmp/netspot_%s_data.json"
# Same as the data but for the alarms
#alarm = "/tmp/netspot_%s_alarm.json"

[exporter.socket]
# Path to the socket which will receive the data
# The format is the following: [proto]://[address]
#data = "unix:///tmp/netspot_data.socket"
# Path to the socket which will receive the alarms
# The format is the following: [proto]://[address]
#alarm = "unix:///tmp/netspot_alarm.socket"
# Additional tag when data are sent
#tag = "netspot"
# Format of the data (accept csv, json or gob)
#format = "json"

# [exporter.influxdb1]
#data = true
#alarm = true
#address = "http://127.0.0.1:8086"
#database = "netspot"
#username = "netspot"
#password = "netspot"
#batch_size = -5
#agent_name = "local"
