# -------------------------------------------------------------------------------------- #
# ----------------------------- NetSpot configuration file ----------------------------- #
# -------------------------------------------------------------------------------------- #

[server]
# log_level defines the verbosity of the server logs 
# (from 0: debug, to 5: panic)
log_level = 1

# http activates the HTTP REST endpoint
http = true

# http_addr defines the ip address and tcp port
# of the HTTP endpoint
http_addr = "127.0.0.1:11000"

# activate TLS (v1.2 only) on the HTTP endpoint (certificate and key must be provided)
# If the certificate is signed by a certificate authority, the cert file 
# should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate. 
tls = false
cert = "extra/cert.pem"
key = "extra/key.pem"

# rpc activates the Golang RPC server. It directly exposes some methods
# which are easy to call from a go-written client. 
rpc = true

# rpc_addr defines the ip address and tcp port
# of the RPC endpoint
rpc_addr = "127.0.0.1:11001"

[miner]
# name of the interface to listen or dump/pcap file path
# device = "eno1"
# device = "/path/to/pcap/file"
# interface only
promiscuous = true
snapshot_len = 65535
timeout = "20s"

[analyzer]
# time between two statistics computations
period = "1s"
# stats to load at startup
#stats = ["AVG_PKT_SIZE"]
# stats = ["PERF", "R_SYN", "R_ACK"]
#stats = []

[data]
# send data to influxdb database
influxdb = false
# log data/thresholds/anomalies to files
file = true
# output_dir is the directory which contains the logs
output_dir = "/tmp" # file mode only

[influxdb]
# influxdb server details
addr = "127.0.0.1"
port = 8086
database = "netspot"
username = "netspot"
password = "netspot"
# number of data to store before sending
batch_size = 10
# the agent_name is just a tag for influxdb
agent_name = "unknown"

[dspot]
# default values of DSpot
depth = 200
q = 5e-5
n_init = 2000
level = 0.99
up = true
down = false
alert = true
bounded = true
max_excess = 200

# you can define default values for some stats
# [dspot.R_SYN]
# q = 2e-5


