// Code generated by bpf2go; DO NOT EDIT.

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadXDP returns the embedded CollectionSpec for XDP.
func LoadXDP() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XDPBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XDP: %w", err)
	}

	return spec, err
}

// LoadXDPObjects loads XDP and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XDPObjects
//	*XDPPrograms
//	*XDPMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXDPObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXDP()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XDPSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPSpecs struct {
	XDPProgramSpecs
	XDPMapSpecs
	XDPVariableSpecs
}

// XDPProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPProgramSpecs struct {
	XdpUpdateCounters *ebpf.ProgramSpec `ebpf:"xdp_update_counters"`
}

// XDPMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPMapSpecs struct {
	NetspotCountersMap    *ebpf.MapSpec `ebpf:"netspot_counters_map"`
	NetspotTcpDstPortsMap *ebpf.MapSpec `ebpf:"netspot_tcp_dst_ports_map"`
}

// XDPVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XDPVariableSpecs struct {
}

// XDPObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPObjects struct {
	XDPPrograms
	XDPMaps
	XDPVariables
}

func (o *XDPObjects) Close() error {
	return _XDPClose(
		&o.XDPPrograms,
		&o.XDPMaps,
	)
}

// XDPMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPMaps struct {
	NetspotCountersMap    *ebpf.Map `ebpf:"netspot_counters_map"`
	NetspotTcpDstPortsMap *ebpf.Map `ebpf:"netspot_tcp_dst_ports_map"`
}

func (m *XDPMaps) Close() error {
	return _XDPClose(
		m.NetspotCountersMap,
		m.NetspotTcpDstPortsMap,
	)
}

// XDPVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPVariables struct {
}

// XDPPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXDPObjects or ebpf.CollectionSpec.LoadAndAssign.
type XDPPrograms struct {
	XdpUpdateCounters *ebpf.Program `ebpf:"xdp_update_counters"`
}

func (p *XDPPrograms) Close() error {
	return _XDPClose(
		p.XdpUpdateCounters,
	)
}

func _XDPClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdp_bpf.o
var _XDPBytes []byte
