name: netspot
version: "2.0a"
summary: A simple IDS with statistical learning
description: |
  netspot is a basic network intrusion detection system
  which aims to detect abnormal behaviours from network
  statistics.
base: core18

grade: devel
confinement: devmode

parts:
  netspot:
    plugin: go
    source-type: local
    source: .
    go-importpath: netspot
    build-packages:
      - gcc
      - git
      - libpcap-dev
    stage-packages:
      - libpcap0.8

apps:
  netspot:
    command: bin/netspot
