name: netspot
version: "2.0a"
summary: A simple IDS with statistical learning
description: |
  netspot is a basic network intrusion detection system
  which aims to detect abnormal behaviours from network
  statistics.
base: core18
icon: assets/favicon-blue.svg
type: app
license: GPL-3.0+

grade: devel
confinement: devmode

parts:
  netspot:
    plugin: go
    go-channel: 1.16/stable
    source: .
    build-packages:
      - gcc
      - git
      - libpcap-dev
    stage-packages:
      - libpcap0.8

apps:
  netspot:
    command: bin/netspot
