name: netspot
version: "1.3"
summary: A basic IDS with statistical learning
description: |
  NetSpot is a basic network intrusion dection system
  which aims to detect abnormal behaviours from network
  measures. It works as a server and can be managed by 
  a client (netspotctl).
base: core18

grade: devel
confinement: devmode

# architectures:
#   - build-on: amd64

parts:
  netspot:
    plugin: go
    source-type: local
    source: .
    go-importpath: netspot
    build-packages:
      - gcc
      - git
      - libpcap-dev
    stage-packages:
      - libpcap0.8

apps:
  netspot:
    daemon: simple
    command: bin/netspot -c $SNAP_COMMON/netspot.toml -l 0
  netspotctl:
    command: bin/netspotctl
