name: Go
on: [push]
jobs:
  build:
    name: Build (amd64)
    env:
      LIBPCAP_VERSION: 1.9.1
      LIBPCAP_BUILD_DIR: /tmp
      PACKAGES: software-properties-common byacc flex dpkg-dev python3 python3-pip debhelper
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install -y $PACKAGES libpcap0.8 libpcap-dev
          make

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: netspot
          path: bin/

      - name: Debian packaging
        run: make debian

      - name: Upload debian package
        uses: actions/upload-artifact@v1
        with:
          name: netspot-debian-amd64
          path: dist/debian/

  build-armhf:
    name: Build (armhf)
    env:
      LIBPCAP_VERSION: 1.9.1
      CC: arm-linux-gnueabihf-gcc
      CGO_ENABLED: 1
      CGO_LDFLAGS: -L/tmp/libpcap-$LIBPCAP_VERSION
      CGO_CFLAGS: -g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION
      GOOS: linux
      GOARCH: arm
      GOARM: 7
      LD_LIBRARY_PATH: /usr/arm-linux-gnueabihf/lib
      PACKAGES: software-properties-common byacc flex dpkg-dev python3 python3-pip debhelper
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Set environment variable
        run: |
          echo ::set-env name=CC::$CC
          echo ::set-env name=CGO_ENABLED::$CGO_ENABLED
          echo ::set-env name=CGO_LDFLAGS::$CGO_LDFLAGS
          echo ::set-env name=CGO_CFLAGS::$CGO_CFLAGS
          echo ::set-env name=GOOS::$GOOS
          echo ::set-env name=GOARCH::$GOARCH
          echo ::set-env name=GOARM::$GOARM

      - name: Compilation of libpcap
        run: |
          sudo apt-get update
          sudo apt-get install -y $PACKAGES linux-libc-dev-armhf-cross gcc-arm-linux-gnueabihf
          cd /tmp
          wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
          tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
          cd libpcap-$LIBPCAP_VERSION
          ./configure --host=arm-linux --with-pcap=linux
          make

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Compilation of netspot for armhf
        run: |
          make
          echo ::set-env name=LD_LIBRARY_PATH::$LD_LIBRARY_PATH

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: netspot-armhf
          path: bin/

      - name: Debian packaging
        run: LD_LIBRARY_PATH=/usr/arm-linux-gnueabihf/lib make debian

      - name: Upload debian package
        uses: actions/upload-artifact@v1
        with:
          name: netspot-debian-armhf
          path: dist/debian/

  build-aarch64:
    name: Build (aarch64)
    env:
      LIBPCAP_VERSION: 1.9.1
      PACKAGES: software-properties-common byacc flex dpkg-dev python3 python3-pip debhelper
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Compilation of libpcap
        run: |
          sudo apt-get update
          sudo apt-get install -y $PACKAGES linux-libc-dev-arm64-cross gcc-aarch64-linux-gnu
          cd /tmp
          wget http://www.tcpdump.org/release/libpcap-$LIBPCAP_VERSION.tar.gz
          tar xvf libpcap-$LIBPCAP_VERSION.tar.gz
          cd libpcap-$LIBPCAP_VERSION
          CC=aarch64-linux-gnu-gcc ./configure --host=arm-linux --with-pcap=linux
          CC=aarch64-linux-gnu-gcc make

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Compilation of netspot for aarch64
        run: |
          export CGO_ENABLED=1
          export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
          export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
          export CC=aarch64-linux-gnu-gcc
          export GOOS=linux
          export GOARCH=arm64
          make

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: netspot-aarch64
          path: bin/
      # - name: Debian packaging
      #   run: |
      #     export CGO_ENABLED=1
      #     export CGO_LDFLAGS=-L/tmp/libpcap-$LIBPCAP_VERSION
      #     export CGO_CFLAGS="-g -O2 -I/tmp/libpcap-$LIBPCAP_VERSION"
      #     export CC=aarch64-linux-gnu-gcc
      #     export GOOS=linux
      #     export GOARCH=arm64
      #     LD_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib make debian
      # - name: Upload debian package
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: netspot-debian-armhf
      #     path: dist/debian/
