name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: make deps

      - name: Build
        run: |
          mkdir -p /home/runner/go/src/netspot
          cp /home/runner/work/netspot/netspot/* /home/runner/go/src/netspot/
          cd /home/runner/go/src/netspot
          ls -al
          make
