name: Build
on:
  repository_dispatch:
    types: update
jobs:
  build:
    name: Build (amd64)
    runs-on: ubuntu-latest
    container: 
      image: golang:1.15.3-alpine
      env:
        LIBPCAP_VERSION: 1.9.1
        LIBPCAP_DIR: /libpcap
        # SYSTEM
        PACKAGES: nano bash linux-headers git flex bison wget make bluez-dev bluez
        CGO_ENABLED: 1
        CGO_LDFLAGS: -L${LIBPCAP_DIR}/libpcap-${LIBPCAP_VERSION}
        CGO_CFLAGS: -O2 -I${LIBPCAP_DIR}/libpcap-${LIBPCAP_VERSION}
        # CROSS COMPILATION OPTIONS
        # see https://github.com/just-containers/musl-cross-make/releases/
        GCC_VERSION: 9.2.0
        MUSL_CROSS_MAKE_VERSION: v15
        TARGET_ARCH: x86_64-linux-musl arm-linux-musleabihf aarch64-linux-musl
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get libpcap sources
        run: dev/image/get_libpcap_sources.sh
      
      - name: Install toolchain
        run: dev/image/install_toolchain.sh

      - name: Build
        run: make

      - name: Upload binaries
        uses: actions/upload-artifact@v1
        with:
          name: netspot
          path: bin/
