name: Build and Push Image
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - 20-docker-distribution

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: asiffer/netspot
        tags: latest ${{ github.sha }}
        dockerfiles: |
          ./Dockerfile

    - name: Push GitHub container registry
      id: push-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: ghcr.io
        username: asiffer
        password: ${{ secrets.GITHUB_TOKEN }}
