name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: golang:1.15.7-alpine
      env:
        # SYSTEM
        PACKAGES: bash linux-headers git git-lfs flex bison wget make bluez-dev bluez libpcap libpcap-dev gcc musl-dev
    services:
      influxdb:
        image: influxdb:1.8
        ports:
        - 8086/tcp
    steps:
      - name: Get packages
        run: apk update; apk add $PACKAGES

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs pull

      - name: Symbolic link to GOPATH
        run: ln -s $GITHUB_WORKSPACE $GOPATH/src/netspot

      - name: Setup CGO env variables
        run: |
          echo CGO_ENABLED=1 >> $GITHUB_ENV

      - name: debug
        run: |
          pwd
          ls -alh --color=auto
          ls -alh test
      - name: Run tests
        run: go test -race -cover -v ./...

