name: Test
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
    - 'docs/**'
    - 'sources/**'
  repository_dispatch:
    types: [release_test]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: 
      image: golang:1.16.3-alpine
      env:
        # SYSTEM
        PACKAGES: bash curl linux-headers git git-lfs flex bison wget make bluez-dev bluez libpcap libpcap-dev gcc musl-dev
    services:
      influxdb:
        image: influxdb:1.8
        ports:
        - 8086/tcp
    steps:
      - name: Get packages
        run: apk update; apk add $PACKAGES

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Symbolic link to GOPATH
        run: ln -s $GITHUB_WORKSPACE $GOPATH/src/netspot

      - name: Setup CGO env variables
        run: |
          echo CGO_ENABLED=1 >> $GITHUB_ENV

      - name: Run tests
        run: |
          make test START_DOCKER_FOR_INFLUXDB=false
          curl -s https://codecov.io/bash > codecov.sh
          bash codecov.sh

      # steps in case of repository_dispatch (release) #
      - name: Trigger build
        if: ${{ github.event_name == 'release_test' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: release_build # trigger build
          client-payload: ${{ github.event.client_payload }} # forward payload to build

