#!/bin/sh

# netspot config file

echo "
[analyzer]
# time between two statistics computations
period = "1s"
# stats to load at startup
#stats = ["AVG_PKT_SIZE"]
stats = ["R_SYN", "R_ACK"]
#stats = []

[analyzer.datalog]
# send data to influxdb database
influxdb = false
# log data to files
file = true
output_dir = $SNAP_DATA # file mode only

[miner]
# name of the interface to listen or dump/pcap file path
#device = "enp2s0"
#device = "enx84a93e22a3fb"
device = "/data/kitsune/Mirai/Mirai_pcap.pcap"
# interface only
promiscuous = true
snapshot_len = 65535
timeout = "20s"

[influxdb]
# influxdb server details
addr = "127.0.0.1"
port = 8086
database = "netspot"
username = "netspot"
password = "netspot"
# number of data to store before sending
batch_size = 10
# the agent_name is just a tag for influxdb
agent_name = "unknown"


[dspot]
# default values of DSpot
depth = 200
q = 1e-4
n_init = 2500
level = 0.99
up = true
down = false
alert = true
bounded = true
max_excess = 200

# you can define default values for some stats
# [dspot.R_SYN]
# q = 2e-5
" > "$SNAP_COMMON/netspot.toml"